/*++

Copyright (C) 2019 Numbers developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++ implementation file in order to allow easy
development of Numbers library. It needs to be generated only once.

Interface version: 1.0.0

*/

#include "numbers_abi.hpp"
#include "numbers_interfaces.hpp"
#include "numbers_interfaceexception.hpp"

#include "numbers_variable.hpp"

using namespace Numbers;
using namespace Numbers::Impl;

Numbers_FunctionTableBase IBase::m_sFunctionTable;
Numbers_FunctionTableVariable IVariable::m_sFunctionTable;

IVariable * CWrapper::CreateVariable(const Numbers_double dInitialValue)
{
	// This should be done in a static way
	IBase::m_sFunctionTable.m_pfnAcquireOwnership = &numbers_acquireinstance;
	IBase::m_sFunctionTable.m_pfnReleaseOwnership = &numbers_releaseinstance;
	IBase::m_sFunctionTable.m_pfnGetLastError = &numbers_getlasterror;

	IVariable::m_sFunctionTable.m_pfnAcquireOwnership = &numbers_acquireinstance;
	IVariable::m_sFunctionTable.m_pfnReleaseOwnership = &numbers_releaseinstance;
	IVariable::m_sFunctionTable.m_pfnGetLastError = &numbers_getlasterror;
	IVariable::m_sFunctionTable.m_pfnSetValue = &numbers_variable_setvalue;
	IVariable::m_sFunctionTable.m_pfnGetValue = &numbers_variable_getvalue;

	return new CVariable();
}

void CWrapper::GetVersion(Numbers_uint32 & nMajor, Numbers_uint32 & nMinor, Numbers_uint32 & nMicro)
{
	nMajor = NUMBERS_VERSION_MAJOR;
	nMinor = NUMBERS_VERSION_MINOR;
	nMicro = NUMBERS_VERSION_MICRO;
}

bool CWrapper::GetLastError(IBase* pInstance, std::string & sErrorMessage)
{
	throw ENumbersInterfaceException(NUMBERS_ERROR_NOTIMPLEMENTED);
}

void CWrapper::ReleaseInstance(IBase* pInstance)
{
	IBase::ReleaseBaseClassInterface(pInstance);
}

void CWrapper::AcquireInstance(IBase* pInstance)
{
	IBase::AcquireBaseClassInterface(pInstance);
}


